"""Generate synthetic building-frame .dat models for performance benchmarking.

The generated model is a regular orthogonal frame: columns on a rectangular
grid, X/Y beams at every floor level, and fixed supports at the base. Load
patterns are opt-in so that a sweep can isolate the cost of each code path
(gravity, point loads, element loads, area loads, rigid diaphragms).

Examples
--------
    python tools/bench/gen_model.py --target-nodes 10000 -o bench_10k.dat
    python tools/bench/gen_model.py --bays-x 8 --bays-y 6 --stories 5 --elod
"""

from __future__ import annotations

import argparse
import math
import os
import sys

_REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
_CLASSES_DIR = os.path.join(_REPO_ROOT, "classes")
for _p in (_CLASSES_DIR, _REPO_ROOT):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from dat_format import (  # noqa: E402
    ALOD_FMTS,
    CONS_FMTS,
    DIAP_FMTS,
    ELEM_FMTS,
    ELOD_FMTS,
    GLOD_FMTS,
    MATE_FMTS,
    NODE_FMTS,
    PLOD_FMTS,
    SECT_FMTS,
    record_line,
    write_dat_text,
)

GRAVITY = 9.80665

# Load case indices used by the generated models.
LC_GRAVITY = 0
LC_WIND_X = 1
LC_WIND_Y = 2
LC_FLOOR = 3


class FrameGrid:
    """Regular bays_x * bays_y * stories orthogonal frame."""

    def __init__(self, bays_x, bays_y, stories, span_x, span_y, story_height):
        if bays_x < 1 or bays_y < 1 or stories < 1:
            raise ValueError("bays_x, bays_y and stories must all be >= 1")
        self.bays_x = bays_x
        self.bays_y = bays_y
        self.stories = stories
        self.span_x = span_x
        self.span_y = span_y
        self.story_height = story_height

    @property
    def nx(self):
        return self.bays_x + 1

    @property
    def ny(self):
        return self.bays_y + 1

    @property
    def nz(self):
        return self.stories + 1

    @property
    def node_count(self):
        return self.nx * self.ny * self.nz

    @property
    def element_count(self):
        columns = self.nx * self.ny * self.stories
        beams_x = self.bays_x * self.ny * self.stories
        beams_y = self.nx * self.bays_y * self.stories
        return columns + beams_x + beams_y

    def node_id(self, i, j, k):
        return (k * self.ny + j) * self.nx + i

    def coords(self, i, j, k):
        return (i * self.span_x, j * self.span_y, k * self.story_height)


def choose_grid(target_nodes, story_height, span_x, span_y, max_stories=80):
    """Pick bays_x/bays_y/stories giving a node count closest to target_nodes.

    Plan dimensions are kept roughly square and at least as large as the
    number of stories, so the result looks like a building rather than a mast.
    """

    best = None
    for stories in range(1, max_stories + 1):
        plan_nodes = target_nodes / float(stories + 1)
        if plan_nodes < 4.0:
            break
        side = max(2, int(round(math.sqrt(plan_nodes))))
        for nx in (side - 1, side, side + 1):
            if nx < 2:
                continue
            ny = max(2, int(round(plan_nodes / nx)))
            if nx < stories + 1 or ny < stories + 1:
                continue
            grid = FrameGrid(nx - 1, ny - 1, stories, span_x, span_y, story_height)
            error = abs(grid.node_count - target_nodes)
            key = (error, abs(nx - ny))
            if best is None or key < best[0]:
                best = (key, grid)
    if best is None:
        raise ValueError("cannot build a grid for target_nodes={0}".format(target_nodes))
    return best[1]


def _materials_and_sections():
    lines = ["# --- MATERIAL(MATE) ---"]
    lines.append(record_line("MATE", MATE_FMTS, [0, "SN400B", 205000, 79000, 78.5, 1.2e-05, 235]))
    lines.append(record_line("MATE", MATE_FMTS, [1, "BCR295", 205000, 79000, 78.5, 1.2e-05, 295]))
    lines.append("")
    lines.append("# --- SECTION(SECT) ---")
    lines.append("#   SEC 0 = column (RHS), SEC 1 = beam (I)")
    lines.append(record_line("SECT", SECT_FMTS, [0, "C1", 1, 4, 400.0, 400.0, 19.0, 19.0]))
    lines.append(record_line("SECT", SECT_FMTS, [1, "G1", 0, 2, 500.0, 200.0, 12.0, 19.0]))
    lines.append("")
    return lines


def build_model_lines(
    grid,
    gravity=True,
    lateral=True,
    elod=False,
    area_loads=False,
    diaphragms=False,
    lateral_kn=5.0,
    elod_kn_per_m=10.0,
    area_kn_per_m2=5.0,
):
    """Return the .dat text lines for one synthetic frame model."""

    lines = [
        "# --- SYNTHETIC BENCHMARK MODEL (generated by tools/bench/gen_model.py) ---",
        "# bays: {0} x {1}, stories: {2}".format(grid.bays_x, grid.bays_y, grid.stories),
        "# nodes: {0}, elements: {1}, dof: {2}".format(
            grid.node_count, grid.element_count, 6 * grid.node_count
        ),
        "# Units: m, kN, kN/m, N/mm2",
        "",
    ]
    lines.extend(_materials_and_sections())

    lines.append("# --- NODE ---")
    for k in range(grid.nz):
        for j in range(grid.ny):
            for i in range(grid.nx):
                x, y, z = grid.coords(i, j, k)
                lines.append(
                    record_line("NODE", NODE_FMTS, [grid.node_id(i, j, k), x, y, z])
                )
    lines.append("")

    lines.append("# --- ELEMENT(ELEM) ---")
    eid = 0
    beam_ids = []
    # beams_x[(i, j, k)] spans from (i, j, k) to (i+1, j, k)
    beams_x = {}
    beams_y = {}
    for k in range(grid.stories):
        for j in range(grid.ny):
            for i in range(grid.nx):
                n0 = grid.node_id(i, j, k)
                n1 = grid.node_id(i, j, k + 1)
                lines.append(record_line("ELEM", ELEM_FMTS, [eid, n0, n1, 0, 0.0]))
                eid += 1
    for k in range(1, grid.nz):
        for j in range(grid.ny):
            for i in range(grid.bays_x):
                n0 = grid.node_id(i, j, k)
                n1 = grid.node_id(i + 1, j, k)
                lines.append(record_line("ELEM", ELEM_FMTS, [eid, n0, n1, 1, 0.0]))
                beams_x[(i, j, k)] = eid
                beam_ids.append(eid)
                eid += 1
        for j in range(grid.bays_y):
            for i in range(grid.nx):
                n0 = grid.node_id(i, j, k)
                n1 = grid.node_id(i, j + 1, k)
                lines.append(record_line("ELEM", ELEM_FMTS, [eid, n0, n1, 1, 0.0]))
                beams_y[(i, j, k)] = eid
                beam_ids.append(eid)
                eid += 1
    lines.append("")

    lines.append("# --- CONSTRAINT(CONS) ---")
    for j in range(grid.ny):
        for i in range(grid.nx):
            lines.append(
                record_line("CONS", CONS_FMTS, [grid.node_id(i, j, 0), 1, 1, 1, 1, 1, 1])
            )
    lines.append("")

    if gravity:
        lines.append("# --- GRAVITY LOAD(GLOD) ---")
        lines.append(record_line("GLOD", GLOD_FMTS, [LC_GRAVITY, 0.0, 0.0, -GRAVITY]))
        lines.append("")

    if lateral:
        lines.append("# --- POINT LOAD(PLOD) ---")
        for k in range(1, grid.nz):
            for j in range(grid.ny):
                for i in range(grid.nx):
                    nid = grid.node_id(i, j, k)
                    lines.append(
                        record_line(
                            "PLOD", PLOD_FMTS,
                            [nid, LC_WIND_X, lateral_kn, 0.0, 0.0, 0.0, 0.0, 0.0],
                        )
                    )
                    lines.append(
                        record_line(
                            "PLOD", PLOD_FMTS,
                            [nid, LC_WIND_Y, 0.0, lateral_kn, 0.0, 0.0, 0.0, 0.0],
                        )
                    )
        lines.append("")

    if elod:
        lines.append("# --- ELEMENT LOAD(ELOD) ---")
        w = -elod_kn_per_m
        for bid in beam_ids:
            lines.append(
                record_line(
                    "ELOD", ELOD_FMTS,
                    [bid, LC_FLOOR, 1, 0.0, 0.0, w, 0.0, 0.0, w],
                )
            )
        lines.append("")

    if area_loads:
        lines.append("# --- AREA LOAD(ALOD) ---")
        pz = -area_kn_per_m2
        for k in range(1, grid.nz):
            for j in range(grid.bays_y):
                for i in range(grid.bays_x):
                    e1 = beams_x[(i, j, k)]
                    e2 = beams_y[(i + 1, j, k)]
                    e3 = beams_x[(i, j + 1, k)]
                    e4 = beams_y[(i, j, k)]
                    lines.append(
                        record_line("ALOD", ALOD_FMTS, [LC_FLOOR, 0.0, 0.0, pz, e1, e2, e3, e4])
                    )
        lines.append("")

    if diaphragms:
        lines.append("# --- DIAPHRAGM REGION(DIAP) ---")
        for k in range(1, grid.nz):
            lines.append(
                record_line(
                    "DIAP", DIAP_FMTS,
                    [k, "FL{0}".format(k), 0, 0, "", "", 0.0, "", ""],
                )
            )
        lines.append("")
        lines.append("# --- DIAPHRAGM OUTER POLYGON(DREG) ---")
        for k in range(1, grid.nz):
            corners = [
                grid.node_id(0, 0, k),
                grid.node_id(grid.nx - 1, 0, k),
                grid.node_id(grid.nx - 1, grid.ny - 1, k),
                grid.node_id(0, grid.ny - 1, k),
            ]
            lines.append(record_line("DREG", [">6"] * 5, [k] + corners))
        lines.append("")

    return lines


def _describe(grid, path, lines):
    return (
        "{0}\n"
        "  bays        : {1} x {2}\n"
        "  stories     : {3}\n"
        "  nodes       : {4}\n"
        "  elements    : {5}\n"
        "  dof         : {6}\n"
        "  .dat lines  : {7}"
    ).format(
        path, grid.bays_x, grid.bays_y, grid.stories,
        grid.node_count, grid.element_count, 6 * grid.node_count, len(lines),
    )


def build_parser():
    p = argparse.ArgumentParser(
        description="Generate a synthetic building-frame .dat model for benchmarking.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    size = p.add_argument_group("model size")
    size.add_argument("--bays-x", type=int, default=4, help="number of bays in X")
    size.add_argument("--bays-y", type=int, default=4, help="number of bays in Y")
    size.add_argument("--stories", type=int, default=4, help="number of stories")
    size.add_argument(
        "--target-nodes", type=int, default=None,
        help="pick bays/stories automatically to approach this node count "
             "(overrides --bays-x/--bays-y/--stories)",
    )
    geom = p.add_argument_group("geometry")
    geom.add_argument("--span-x", type=float, default=6.0, help="bay span in X [m]")
    geom.add_argument("--span-y", type=float, default=6.0, help="bay span in Y [m]")
    geom.add_argument("--story-height", type=float, default=3.5, help="story height [m]")

    loads = p.add_argument_group("load patterns")
    loads.add_argument("--no-gravity", dest="gravity", action="store_false",
                       help="omit the GLOD self-weight load case")
    loads.add_argument("--no-lateral", dest="lateral", action="store_false",
                       help="omit the PLOD lateral load cases")
    loads.add_argument("--elod", action="store_true",
                       help="add a uniform ELOD line load on every beam "
                            "(exercises the per-element load lookup path)")
    loads.add_argument("--area-loads", action="store_true",
                       help="add an ALOD panel load on every floor bay "
                            "(exercises the tributary-area grid)")
    loads.add_argument("--diaphragms", action="store_true",
                       help="add a rigid diaphragm per floor "
                            "(exercises the MPC reduction path)")
    loads.add_argument("--lateral-kn", type=float, default=5.0, help="PLOD magnitude [kN]")
    loads.add_argument("--elod-kn-per-m", type=float, default=10.0, help="ELOD magnitude [kN/m]")
    loads.add_argument("--area-kn-per-m2", type=float, default=5.0, help="ALOD magnitude [kN/m2]")

    p.add_argument("-o", "--output", required=True, help="output .dat path")
    p.add_argument("-q", "--quiet", action="store_true", help="suppress the summary")
    return p


def main(argv=None):
    args = build_parser().parse_args(argv)

    if args.target_nodes is not None:
        grid = choose_grid(
            args.target_nodes, args.story_height, args.span_x, args.span_y
        )
    else:
        grid = FrameGrid(
            args.bays_x, args.bays_y, args.stories,
            args.span_x, args.span_y, args.story_height,
        )

    lines = build_model_lines(
        grid,
        gravity=args.gravity,
        lateral=args.lateral,
        elod=args.elod,
        area_loads=args.area_loads,
        diaphragms=args.diaphragms,
        lateral_kn=args.lateral_kn,
        elod_kn_per_m=args.elod_kn_per_m,
        area_kn_per_m2=args.area_kn_per_m2,
    )

    out_dir = os.path.dirname(os.path.abspath(args.output))
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    write_dat_text(args.output, "\n".join(lines))

    if not args.quiet:
        print(_describe(grid, args.output, lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
